- name: Update root password
  user: name=root password="{{ common_root_password }}"

- name: Update APT package cache
  apt: update_cache=yes cache_valid_time=3600

- name: Upgrade APT to the latest packages
  apt: upgrade=safe

- name: Install required packages
  apt: state=installed pkg={{ item }}
  with_items: common_required_packages

- name: Install optional packages
  apt: state=installed pkg={{ item }}
  with_items: common_optional_packages
  when: with_optional_packages
