- name: Install sshd configuration
  template: src=ssh/sshd_config.j2 dest=/etc/ssh/sshd_config owner=root group=root mode=0644
  notify:
    - Restart ssh

- name: Ensure ssh is running
  service: name=ssh state=started
